services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
    logging:
      driver: none

  mongo:
    image: mongo
    container_name: pa-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ADMINUSERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ADMINPASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    volumes: 
      - ./mongodb:/docker-entrypoint-initdb.d
      - ./mongodb/data:/data/db
    logging:
      driver: none

  python:
    container_name: python_service_DL
    build: ./python
    ports:
      - 5001:5001
    restart: unless-stopped

  node:
    container_name: node-prod
    hostname: node-prod
    build: ./backend
    ports:
      - 3000:8081
    environment:
      - MONGO_URI=mongodb://mongo:$MONGODB_PORT/$MONGODB_DATABASE
      - MONGO_USER=$MONGODB_ADMINUSERNAME
      - MONGO_PASS=$MONGODB_ADMINPASSWORD
      - REDIS_URI=redis://redis:$REDIS_PORT
      - PYTHON_URI=http://python:$PYTHON_PORT
    depends_on:
      - redis
      - mongo
      - python
    restart: unless-stopped
    volumes: 
      - ./logs:/usr/src/app/logs