services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  mongo:
    image: mongo
    container_name: pa-mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ADMINUSERNAME
        - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ADMINPASSWORD
        - MONGO_INITDB_DATABASE=project
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: pa-mongo-express
    environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_ADMINUSERNAME
       - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_ADMINPASSWORD
       - ME_CONFIG_MONGODB_SERVER=$MONGODB_SERVER
       - ME_CONFIG_MONGODB_PORT=$MONGODB_PORT
    depends_on:
        - mongo
    ports:
      - 8082:8081

  node:
    container_name: node-dev
    image: node-dev
    hostname: node-dev
    ports:
        - 3000:3000
    depends_on:
        - redis
        - mongo